# For more information: https://laravel.com/docs/sail
version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  node:
    image: "node:8"
    user: "node"
    working_dir: /var/www/html
    environment:
      - NODE_ENV=production
    volumes:
      - .:/var/www/html
    expose:
      - "8081"
    command: bash -c "npm install && npm run dev"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
networks:
  laravel:



